parties:
  Ap: Arbeiderpartiet
  H: Høyre
  FrP: Fremskrittspartiet
  SV: Sosialistisk Venstreparti
  Sp: Senterpartiet
  V: Venstre
  KrF: Kristelig Folkeparti
  MDG: Miljøpartiet De Grønne
  R: Rødt
  Andre: Andre
